Repository umr-lops/sarwaveifrproc, pull requests merged in 2024-04, with the labels that each got.

#4 PR from `dev` branch to mitigate issue with `burst` dimension missing
  sarwaveifrproc/l2_wave.py
  sarwaveifrproc/reference_data/s1a-iw2-slc-dv-20231128t035702-20231128t035727-051412-063451-e01.nc
  sarwaveifrproc/reference_data/s1a-iw2-slc-vh-20231128t035702-20231128t035727-051412-063451-002_L1B_xspec_IFR_3.7.6nospectra.nc
  sarwaveifrproc/reference_data/s1a-iw2-slc-vv-20231128t035702-20231128t035727-051412-063451-005_L1B_xspec_IFR_3.7.6nospectra.nc
  sarwaveifrproc/utils.py
  tests/test_predict.py
Labels: enhancement

#2 Processing functions to process l1b and l1c files to l2 wave
  pyproject.toml
  sarwaveifrproc/config.yaml
  sarwaveifrproc/l2_wave.py
  sarwaveifrproc/main.py
  sarwaveifrproc/reference_data/s1a-iw2-slc-dv-20231128t035702-20231128t035727-051412-063451-e01.nc
  sarwaveifrproc/reference_data/s1a-iw2-slc-vh-20231128t035702-20231128t035727-051412-063451-002_L1B_xspec_IFR_3.7.6nospectra.nc
  sarwaveifrproc/reference_data/s1a-iw2-slc-vv-20231128t035702-20231128t035727-051412-063451-005_L1B_xspec_IFR_3.7.6nospectra.nc
  sarwaveifrproc/utils.py
  tests/test_predict.py
Labels: enhancement

#6 fix logging verbosity
  .github/workflows/publish.yml
  sarwaveifrproc/__init__.py
  sarwaveifrproc/l2_wave.py
  sarwaveifrproc/main.py
Labels: bug

#1 add a Product Description for Ifremer Sentinel-1 Level-2 WAVE
  .gitignore
  AUTHORS.rst
  CONTRIBUTING.rst
  README.rst
  docs/_static/css/sarwaveifrproc.css
  docs/atbd.rst
  docs/bibliography.rst
  docs/conf.py
  docs/figures/ATBD_coarse_idea.png
  docs/figures/attrs_intra.png
  docs/figures/coordinates.png
  docs/figures/coordinates_intra.png
  docs/figures/cover.png
  docs/figures/level2_variables_grids.png
  docs/figures/sar_cross_spectrum.png
  docs/figures/variables_inter.png
  docs/figures/variables_intra.png
  docs/index.rst
  docs/installation.rst
  docs/modules.rst
  docs/product_description.rst
  docs/refs.bib
  docs/usage.rst
  sarwaveifrproc/main.py
  sarwaveifrproc/utils.py
  tests/test_output_names.py
Labels: bug, documentation, enhancement
